In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.cross_validation import train_test_split

C:\Users\PUNIA\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [2]:
df=pd.read_csv("minst.csv")

In [3]:
df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
x=df.iloc[:,1:].values

In [5]:
y=df.iloc[:,0:1].values

In [6]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [7]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier()

In [8]:
classifier.fit(x_train,y_train)

C:\Users\PUNIA\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """Entry point for launching an IPython kernel.

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [9]:
y_pred=classifier.predict(x_test)

In [10]:
prediction=pd.DataFrame({'Actual':list(y_test),'Prediction':list(y_pred)})
prediction

     Actual  Prediction
0       [3]           3
1       [6]           6
2       [9]           9
3       [5]           5
4       [6]           6
5       [5]           5
6       [6]           6
7       [0]           0
8       [0]           0
9       [1]           1
10      [7]           7
11      [1]           1
12      [5]           5
13      [7]           7
14      [8]           8
15      [1]           1
16      [1]           1
17      [5]           5
18      [9]           9
19      [6]           6
20      [9]           9
21      [2]           2
22      [2]           2
23      [8]           8
24      [4]           4
25      [6]           6
26      [2]           2
27      [5]           5
28      [4]           4
29      [4]           4
...     ...         ...
8370    [8]           8
8371    [6]           6
8372    [4]           4
8373    [3]           3
8374    [5]           5
8375    [0]           0
8376    [9]           9
8377    [4]           4
8378    [0]           0
8379    [5]           5
8380    [4]           4
8381    [7]           7
8382    [4]           4
8383    [2]           2
8384    [6]           6
8385    [4]           4
8386    [4]           4
8387    [1]           1
8388    [0]           0
8389    [7]           7
8390    [3]           3
8391    [9]           9
8392    [9]           9
8393    [6]           6
8394    [6]           6
8395    [9]           9
8396    [2]           2
8397    [2]           2
8398    [7]           7
8399    [2]           2

[8400 rows x 2 columns]

In [11]:
from sklearn.metrics import accuracy_score

In [12]:
acc=accuracy_score(y_test,y_pred)
acc

0.9680952380952381