In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import load_wine
data = load_wine()

In [3]:
x=data['data']

In [4]:
y=data['target']

In [5]:

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0,test_size=0.2)

# Bagged Decision Trees

In [6]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import KFold

kfold = KFold(n_splits=10, random_state=0)
m = DecisionTreeClassifier()
model = BaggingClassifier(base_estimator=m, random_state=0)
model.fit(x_train,y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=10, n_jobs=1, oob_score=False,
         random_state=0, verbose=0, warm_start=False)

In [7]:
y_pred=model.predict(x_test)

In [8]:
pd.DataFrame({'Actual':y_test,'Predicted':y_pred})

    Actual  Predicted
0        0          0
1        2          2
2        1          1
3        0          0
4        1          1
5        1          0
6        0          0
7        2          2
8        1          1
9        1          1
10       2          2
11       2          2
12       0          0
13       1          1
14       2          2
15       1          1
16       0          0
17       0          0
18       1          2
19       0          0
20       1          1
21       0          0
22       0          0
23       1          1
24       1          1
25       1          1
26       1          0
27       1          1
28       1          1
29       2          2
30       0          0
31       0          0
32       1          1
33       0          0
34       0          0
35       0          0

In [9]:
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_pred)
print("Accuracy Score is",score)

Accuracy Score is 0.9166666666666666

# Random Forest Classification

In [10]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(criterion='entropy',random_state=0)
classifier.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [11]:
y_pred=classifier.predict(x_test)

In [12]:
pd.DataFrame({'Actual':y_test,'Predicted':y_pred})

    Actual  Predicted
0        0          0
1        2          2
2        1          1
3        0          0
4        1          1
5        1          1
6        0          0
7        2          2
8        1          1
9        1          1
10       2          2
11       2          2
12       0          0
13       1          1
14       2          2
15       1          1
16       0          0
17       0          0
18       1          1
19       0          0
20       1          0
21       0          0
22       0          0
23       1          1
24       1          1
25       1          1
26       1          1
27       1          1
28       1          1
29       2          2
30       0          0
31       0          0
32       1          1
33       0          0
34       0          0
35       0          0

# Stochastic Gradient Boosting Classification

In [14]:
from sklearn.ensemble import GradientBoostingClassifier

model = GradientBoostingClassifier(random_state=0)
model.fit(x_train,y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              presort='auto', random_state=0, subsample=1.0, verbose=0,
              warm_start=False)

In [15]:
y_pred=model.predict(x_test)

In [16]:
pd.DataFrame({'Actual':y_test,'Predicted':y_pred})

    Actual  Predicted
0        0          0
1        2          2
2        1          1
3        0          0
4        1          1
5        1          0
6        0          0
7        2          2
8        1          1
9        1          1
10       2          2
11       2          2
12       0          0
13       1          1
14       2          2
15       1          1
16       0          0
17       0          0
18       1          2
19       0          0
20       1          1
21       0          0
22       0          0
23       1          1
24       1          1
25       1          1
26       1          1
27       1          1
28       1          1
29       2          2
30       0          0
31       0          0
32       1          1
33       0          0
34       0          0
35       0          0

In [17]:
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_pred)
print("Accuracy Score is",score)

Accuracy Score is 0.9444444444444444

# Voting Ensemble

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier

In [19]:
estimators = []
model1 = LogisticRegression()
estimators.append(('logistic', model1))
model2 = DecisionTreeClassifier()
estimators.append(('cart', model2))
model3 = SVC()
estimators.append(('svm', model3))
ensemble = VotingClassifier(estimators)

In [20]:
ensemble.fit(x_train,y_train)
y_pred=ensemble.predict(x_test)

C:\Users\A\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

In [21]:
pd.DataFrame({'Actual':y_test,'Predicted':y_pred})

    Actual  Predicted
0        0          0
1        2          2
2        1          1
3        0          0
4        1          1
5        1          1
6        0          0
7        2          2
8        1          1
9        1          1
10       2          2
11       2          2
12       0          0
13       1          1
14       2          2
15       1          1
16       0          0
17       0          0
18       1          1
19       0          0
20       1          1
21       0          0
22       0          1
23       1          1
24       1          1
25       1          1
26       1          1
27       1          1
28       1          1
29       2          2
30       0          0
31       0          0
32       1          1
33       0          0
34       0          0
35       0          0

In [22]:
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_pred)
print("Accuracy Score is",score)

Accuracy Score is 0.9722222222222222